# Generated by Django 5.1.4 on 2024-12-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contant',
            new_name='Contact',
        ),
    ]
